### ISSUE TITLE
unauthorized to login :|

### ISSUE THREAD

**Issue by voordev** [sanity-io/startup-starter-kit#4]
Cannot login because of errors.
Restored my personal sanity account with a new password it failed.
Tried different browsers.

Was just curious to testdrive the UI.
Shame you have 'vendor lock in' if your service is down you will be unable to edit anything?

**Comment by kmelve** [comment]
Hi @voordev! Cool that you want to try Sanity.io, and I'm very sorry that you experience trouble with our service, could you please contact us on [hello@sanity.io](mailto:hello@sanity.io) and give us some details on which email you use for your account? I'm sure we'll be able to sort this out. 

It's true that you won't be able to use our service if we're not online, just as you can't use GitHub, Gmail, or other “Software as a Service” if they have downtime. We take however stability and uptime _very_ seriously, since it is at the core of what we do.

**Comment by voordev** [comment]
Thank you we will look for another solution, just thought it was worth mentioning the login issues.
